name: bios8366

channels:
 - conda-forge
 
dependencies:
- python
- cython
- ipython
- jupyterlab
- notebook
- ipyparallel
- ipykernel
- line_profiler
- mkl-service
- numpy
- pandas
- patsy
- pip
- pprofile
- proj
- python-graphviz
- rpy2  
- scipy
- snakeviz
- sympy
- xlrd
- pip:
  - catboost
  - jax
  - numba
  - git+https://github.com/pymc-devs/pymc.git
  - bokeh
  - arviz
  - patsy
  - scikit-learn
  - seaborn
  - pyarrow
  - numexpr
  - basemap
