name: bios8366

channels:
 - conda-forge
 
dependencies:
- python
- basemap
- bokeh
- cython
- ipython
- jupyter
- jupyterlab
- notebook
- ipyparallel
- ipywidgets
- jupyter_client
- jupyter_core
- line_profiler
- numexpr
- numba
- numpy
- pandas
- patsy
- pip
- pprofile
- rpy2  
- scikit-learn
- scipy
- seaborn
- snakeviz
- sympy
- pytorch
- catboost
- xlrd
- pymc3